#
# Makefile for phoenix-rtos-lwsip
#
# IA32 qemu dependend part
#
# Copyright 2019 Phoenix Systems
#

NET_DRIVERS = pppos rtl
DRIVERS_SRCS_RTL = rtl8139cp.c $(DRIVERS_SRCS_PCI_IA32) $(DRIVERS_SRCS_UTIL)
DRIVERS_SRCS += $(DRIVERS_SRCS_PPPOS) $(DRIVERS_SRCS_RTL)
