#
# Makefile for phoenix-rtos-lwsip
#
# iMX6ULL dependend part
#
# Copyright 2019 Phoenix Systems
#

NET_DRIVERS += pppos enet tuntap
DRIVERS_SRCS_ENET = imx6-enet.c ephy.c gpio.c imx6ull-gpio.c $(DRIVERS_SRCS_UTIL) hw-debug.c
DRIVERS_SRCS += $(DRIVERS_SRCS_PPPOS) $(DRIVERS_SRCS_ENET) $(DRIVERS_SRCS_TUNTAP)
