#
# Makefile for phoenix-rtos-lwip
#
# Copyright 2019-2021 Phoenix Systems
#
# %LICENSE%
#

NAME := wifi-hal

LOCAL_SRCS := cyhal_gpio.c cyhal_sdio.c cyhal_utils.c cyabs_rtos.c cy_log.c

LOCAL_CFLAGS += -Idrivers

include $(static-lib.mk)
