#
# Makefile for Phoenix-RTOS 3 LwIP
#
# iMX6ULL target
#
# Copyright 2020 Phoenix Systems
#

NET_DRIVERS_SUPPORTED := enet tuntap
NET_DRIVERS ?= $(NET_DRIVERS_SUPPORTED)

DRIVERS_SRCS_enet = imx-enet.c ephy.c imx6ull-gpio.c physelftest.c $(DRIVERS_SRCS_UTIL) hw-debug.c