#
# Makefile for Phoenix-RTOS 3 LwIP
#
# iMX RT1064 target
#
# Copyright 2021 Phoenix Systems
#

NET_DRIVERS_SUPPORTED := enet tuntap
NET_DRIVERS ?= $(NET_DRIVERS_SUPPORTED)

DRIVERS_SRCS_enet = common-enet.c imxrt-enet.c imxrt-ephy.c imxrt-gpio.c $(DRIVERS_SRCS_UTIL) hw-debug.c
