#
# Makefile for Phoenix-RTOS 3 LwIP
#
# iMX6ULL target
#
# Copyright 2020 Phoenix Systems
#

NET_DRIVERS_SUPPORTED := enet tuntap pppou pppos
NET_DRIVERS ?= $(NET_DRIVERS_SUPPORTED)

PPPOS_MODEM ?= huawei

DRIVERS_SRCS_enet = imx-enet.c ephy/ephy.c imx6ull-gpio.c $(DRIVERS_SRCS_UTIL) hw-debug.c
