#
# Makefile for Phoenix-RTOS 3 LwIP
#
# Zynq Ultrascale target
#
# Copyright 2026 Phoenix Systems
#

NET_DRIVERS_SUPPORTED := pppos zynq
NET_DRIVERS ?= $(NET_DRIVERS_SUPPORTED)
PPPOS_MODEM := quectel_rm500u
DRIVERS_SRCS_zynq = zynq-gem.c ephy_alaska.c null-gpio.c $(DRIVERS_SRCS_UTIL)
