#
# Makefile for Phoenix-RTOS 3 LwIP
#
# i.MX RT117x target
#
# Copyright 2022 Phoenix Systems
#

NET_DRIVERS_SUPPORTED := pppou pppos enet
NET_DRIVERS ?= $(NET_DRIVERS_SUPPORTED)
PPPOS_MODEM ?= huawei

DRIVERS_SRCS_enet = imx-enet.c ephy.c imxrt-gpio.c physelftest.c $(DRIVERS_SRCS_UTIL) hw-debug.c
