#
# Makefile for Phoenix-RTOS 3 LwIP
#
# Copyright 2024 Phoenix Systems
#

NET_DRIVERS_SUPPORTED := pppou pppos
ifeq ($(LWIP_G3_BUILD), yes)
NET_DRIVERS_SUPPORTED += g3plc
endif
NET_DRIVERS ?= $(NET_DRIVERS_SUPPORTED)
PPPOS_MODEM := huawei
