#
# Makefile for Phoenix-RTOS 3 LwIP
#
# ia32/QEMU target
#
# Copyright 2020 Phoenix Systems
#

NET_DRIVERS_SUPPORTED := rtl tuntap
NET_DRIVERS ?= $(NET_DRIVERS_SUPPORTED)

DRIVERS_SRCS_PCI_IA32 := pci.c pci-x86.c
DRIVERS_SRCS_rtl = rtl8139cp.c $(DRIVERS_SRCS_PCI_IA32) $(DRIVERS_SRCS_UTIL)
