#define LWIP_TCPIP_CORE_LOCKING 1
#define LWIP_HAVE_SLIPIF 0
#define LWIP_NETIF_API 1
#define LWIP_SOCKET 1
#define LWIP_ARP 1
#define LWIP_ICMP 1
#define LWIP_DHCP 1
#define LWIP_AUTOIP 1
#define LWIP_UDP 1
#define LWIP_TCP 1
#define MEM_LIBC_MALLOC 1
#define LWIP_ERRNO_INCLUDE <errno.h>

#define IP_REASSEMBLY 1
#define IP_FRAG 1

#define ETH_PAD_SIZE 2
#define PBUF_POOL_SIZE 16
#define PBUF_POOL_BUFSIZE 4096
#define DEFAULT_THREAD_STACKSIZE 4096
#define TCPIP_THREAD_STACKSIZE 4096
#define TCPIP_THREAD_PRIO 4
#define TCPIP_MBOX_SIZE 64
